"""
Preprocess/data_driven_prior_network.py
========================================

Implements requirements 2 and 3 of the "biological prior network data-driven
upgrade" spec:

  requirement 2 - once a biological prior-knowledge network has been
  resolved (uploaded, or generated by FLASH-P), optionally build a SECOND,
  data-driven interaction network over the SAME markers RF filtering
  selected (Preprocess/RF_marker_filtering.py's top-M/top-Y% marker set),
  using the identical pairwise-Shapley-interaction algorithm
  models/GAT_prior_knowledge.py already uses - just restricted to that
  smaller, RF-selected marker set instead of every marker, and reusing RF
  filtering's own fitted forest's hyperparameters (with an optional
  n_estimators override) rather than hardcoding new ones.

  requirement 3 - merge that data-driven network into the biological
  network:
    - a data-driven edge between two markers that both fall inside the
      SAME gene's window: no-op (they're already the same graph node).
    - a data-driven edge between a marker inside a gene's window and a
      marker with no gene (a "bare" marker, RF-selected but outside every
      gene): an edge from the bare-marker node to that gene node.
    - a data-driven edge between two markers in DIFFERENT genes' windows:
      an edge between those two gene nodes, if one doesn't already exist.
    - a data-driven edge between two bare markers: an edge between their
      two bare-marker nodes.
  Every resulting node - gene or bare-marker - still gets a self-loop, via
  the SAME blanket self-loop step models/GAT_biological_prior_knowledge.py
  already applies to every node in its (extended) node list; nothing here
  needs to special-case self-loops itself.

Design note - why this is a separate module and not inlined into
models/GAT_biological_prior_knowledge.py
--------------------------------------------------------------------------
Keeping the RF-selection + Shapley-interaction-search + network-merge logic
here, called from GAT_biological_prior_knowledge.py rather than written
inline there, mirrors how Preprocess/gene_network_prior.py already holds
the "biological network -> gene list + gene-gene adjacency" logic the model
file calls into: the model file orchestrates graph *construction* for
PyTorch Geometric, while the actual data-driven decisions (which markers
survive, which pairs interact, how the two networks combine) live in a
plain-pandas/numpy module that's easy to unit test and reuse (e.g. from
genomic_prediction.py's own "other models restricted to this marker pool"
preview logic - see OTHER_MODELS_MARKER_SOURCE == 'gene_network_plus_rf').
"""

import numpy as np
import pandas as pd
import shap
from itertools import product
from sklearn.ensemble import RandomForestRegressor

from Preprocess.RF_marker_filtering import select_rf_markers


def select_markers_for_data_driven_network(train_x, train_y, rf_config):
    """Requirement 2: "reuse the trained RF used in the RF filtering" to
    decide which markers feed the data-driven network - i.e. run the exact
    same selection RF_marker_filtering() would (same config, same
    percent/count mode), on the SAME (train_x, train_y) RF filtering itself
    would see.

    This is a thin, explicitly-named wrapper around
    Preprocess.RF_marker_filtering.select_rf_markers - kept as its own
    function (rather than calling select_rf_markers directly from
    GAT_biological_prior_knowledge.py) so the "requirement 2" intent is
    named at the call site, and so a future change to exactly what "reuse
    RF filtering" means only has one place to change.

    Returns
    -------
    (selected_markers, fitted_rf) : (list of str, RandomForestRegressor)
        selected_markers is in original column order (see
        select_rf_markers's own docstring); fitted_rf is the forest fit on
        every marker in train_x (i.e. BEFORE narrowing to
        selected_markers) - kept only for its hyperparameters (n_estimators
        etc.), read back out in compute_data_driven_interactions() below,
        since a forest fit on the full marker set cannot itself be reused
        for shap_interaction_values() restricted to a narrower column set.
    """
    selected_markers, fitted_rf, _ = select_rf_markers(train_x, train_y, rf_config)
    return selected_markers, fitted_rf


def compute_data_driven_interactions(train_x_selected, train_y, base_rf_config, top_rate,
                                       n_estimators_override=None, sample_size=50, random_state=40):
    """Requirement 2: the SAME pairwise-Shapley-interaction algorithm as
    models/GAT_prior_knowledge.py's own RF+SHAP interaction search
    (fit RF -> shap.TreeExplainer -> shap_interaction_values -> upper
    triangle -> top `top_rate` percent of pairs), but:
      - restricted to `train_x_selected`'s columns (the RF-selected marker
        subset from select_markers_for_data_driven_network above) instead
        of every marker in the genotype table, and
      - fit with `base_rf_config`'s own hyperparameters (mirroring the RF
        filtering forest's own configuration, per requirement 2's "reuse
        the trained RF used in the RF filtering") rather than
        GAT_prior_knowledge.py's hardcoded n_estimators=500, except that
        n_estimators itself can be overridden specifically for this step
        via `n_estimators_override` (e.g. because a forest tuned for
        importance-ranking over thousands of markers may want more/fewer
        trees than one used only for a SHAP interaction search over a much
        smaller, already-narrowed marker set).

    A fresh forest - not the forest fit on the full marker set by
    select_markers_for_data_driven_network - MUST be fit here: SHAP's
    TreeExplainer needs a model trained on exactly the feature columns it
    will be asked to explain, and the full-marker-set forest was trained on
    a different (larger) column set entirely.

    Parameters
    ----------
    train_x_selected : pd.DataFrame
        Genotype columns for the RF-selected markers ONLY (i.e.
        train_x[selected_markers] from the caller).
    train_y : pd.Series
        The training phenotype.
    base_rf_config : dict
        The SAME rf_config shape RF_marker_filtering.py accepts
        ('n_estimators', 'max_depth', 'max_features', 'min_samples_leaf',
        'random_state') - reused here for consistency with the filtering
        forest's own hyperparameters, per requirement 2.
    top_rate : float
        Top N percent (0, 100] of pairwise interaction strengths to keep -
        same meaning and convention as models/GAT_prior_knowledge.py's own
        `top_rate` parameter.
    n_estimators_override : int or None
        If given, used in place of base_rf_config['n_estimators'] for THIS
        forest only (does not affect RF filtering's own forest).
    sample_size : int, default 50
        Individuals sampled for shap_interaction_values(), exactly
        mirroring GAT_prior_knowledge.py's own hardcoded 50.
    random_state : int, default 40
        Mirrors GAT_prior_knowledge.py's own hardcoded random_state=40 for
        this forest, kept as a default rather than reusing
        base_rf_config['random_state'] so results are reproducible/
        comparable against the plain (non-biological-prior) GAT_prior_
        knowledge model's own interaction search run on the same data,
        unless the caller deliberately overrides it.

    Returns
    -------
    pair : pd.DataFrame, columns ['marker_1', 'marker_2', 'value']
        One row per kept unordered pair (marker_1, marker_2 are real
        marker NAMES, not positional indices - unlike GAT_prior_knowledge.py's
        own internal `pair`, which stays purely positional since it never
        needs to leave that function). Empty (zero rows, correct columns)
        if train_x_selected has fewer than 2 columns, since no pair can be
        formed.
    """
    if top_rate is None or not (0 < top_rate <= 100):
        raise ValueError(f"top_rate must be in (0, 100], got {top_rate!r}")

    marker_names = list(train_x_selected.columns)
    if len(marker_names) < 2:
        return pd.DataFrame(columns=['marker_1', 'marker_2', 'value'])

    n_estimators = n_estimators_override if n_estimators_override is not None else base_rf_config.get('n_estimators', 500)
    rf = RandomForestRegressor(
        n_estimators=int(n_estimators),
        max_depth=base_rf_config.get('max_depth', None),
        max_features=base_rf_config.get('max_features', 'sqrt'),
        min_samples_leaf=base_rf_config.get('min_samples_leaf', 1),
        random_state=random_state,
        n_jobs=-1,
    )
    rf.fit(train_x_selected, train_y)

    # From here on, byte-for-byte the same recipe as
    # models/GAT_prior_knowledge.py's own interaction search, just indexed
    # by marker NAME afterwards instead of staying purely positional.
    explainer = shap.TreeExplainer(rf)
    sample_n = min(sample_size, train_x_selected.shape[0])
    f_imp_inter = abs(explainer.shap_interaction_values(shap.sample(train_x_selected, sample_n)).sum(axis=0))
    np.fill_diagonal(f_imp_inter, 0)
    mask = np.ones(f_imp_inter.shape, dtype='bool')
    mask[np.triu_indices(len(f_imp_inter))] = False
    f_imp_inter[mask == False] = 0
    f_imp_inter = pd.DataFrame(f_imp_inter, index=marker_names, columns=marker_names).fillna(0)

    pair = pd.DataFrame(product(marker_names, marker_names), columns=['marker_1', 'marker_2'])
    pair = pd.concat([pair, f_imp_inter.melt().iloc[:, 1]], axis=1)
    pair.columns = ['marker_1', 'marker_2', 'value']
    pair = pair[pair['value'] > 0].reset_index(drop=True)
    n_candidate_pairs = pair.shape[0]
    # Note for anyone eyeballing this against a manual "n choose 2" sanity
    # check: n_candidate_pairs is capped at len(marker_names) * (len(marker_names) - 1) / 2
    # - the number of UNIQUE unordered marker pairs - not
    # len(marker_names) * (len(marker_names) - 1) (which would double-count
    # every pair as both (i, j) and (j, i)). SHAP interaction values are
    # symmetric (interaction[i, j] == interaction[j, i] - "how much i and j
    # interact" isn't directional), so the upper triangle is zeroed above
    # specifically to avoid that double-count; n_candidate_pairs can be
    # smaller still if some pairs have exactly zero interaction.
    print(f"[data_driven_prior_network] {n_candidate_pairs} unique marker pair(s) with a "
          f"nonzero interaction score (out of at most {len(marker_names) * (len(marker_names) - 1) // 2} "
          f"possible unique pairs among {len(marker_names)} markers) - keeping the top {top_rate}% "
          f"of these by interaction strength.")
    if pair.shape[0] == 0:
        return pair
    pair = pair[pair['value'] >= np.quantile(pair['value'].to_numpy().flatten(), 1 - (top_rate / 100))]
    return pair.reset_index(drop=True)


def merge_biological_and_data_driven_networks(gene_to_markers, pair_df, rf_selected_markers, marker_info):
    """Requirement 3: merge the data-driven pairwise-interaction network
    (`pair_df`, from compute_data_driven_interactions above) into the
    biological network's already gene-row-compacted `gene_to_markers`
    (index i <-> the i-th ACTIVE gene node - i.e. gene_to_markers as built
    by models/GAT_biological_prior_knowledge.py right before its self-loop
    step, after empty genes have already been dropped and rows re-indexed).

    Every RF-selected marker that isn't covered by any active gene becomes
    its own new "bare marker" node, appended after the existing gene nodes
    (indices n_genes, n_genes+1, ...) - this is requirement 5's upgrade of
    the old orphan-independent-node mechanism: instead of turning EVERY
    marker outside every gene into an isolated, self-loop-only node, only
    RF-selected markers become nodes at all, and they can have real,
    data-driven edges to other nodes (gene or bare), not just a self-loop.

    Parameters
    ----------
    gene_to_markers : list of list of str
        gene_to_markers[g] = every marker covering active gene node g (the
        FULL covering-marker set, not narrowed to RF-selected markers -
        see the module-level design note in models/GAT_biological_prior_
        knowledge.py for why gene coverage must stay based on the full
        marker set even when this merge feature is in use).
    pair_df : pd.DataFrame, columns ['marker_1', 'marker_2', 'value']
        From compute_data_driven_interactions - both markers are always
        drawn from rf_selected_markers (the function it was built from
        never sees any other marker).
    rf_selected_markers : list of str
        Every marker RF filtering selected for the data-driven network
        (requirement 2) - used here only to decide which markers are
        eligible to become bare nodes (a marker interacting in pair_df but
        outside every gene window must, by construction, be in this list;
        this parameter exists mainly so bare-node coordinates can be looked
        up deterministically even for a marker that ends up with no
        surviving pair after top_rate filtering - see `bare_marker_names`
        below, which is drawn from pair_df's own markers only, so this
        parameter is currently used purely for the sanity check below).
    marker_info : pd.DataFrame
        Columns chromosome, name, start, end (same file
        models/GAT_biological_prior_knowledge.py already loaded) - used to
        look up each bare marker's own coordinates for its gene_list row.

    Returns
    -------
    bare_marker_names : list of str
        RF-selected markers, in pair_df, that fall outside every gene's
        window - the new bare-marker nodes, in a stable (first-seen-in-
        pair_df) order.
    bare_rows : pd.DataFrame, columns ['name', 'chromosome', 'start', 'end']
        One row per bare marker, ready to be appended to gene_list_active.
    bare_gene_to_markers : list of list of str
        One singleton list per bare marker (`[marker_name]`), ready to be
        appended to gene_to_markers - so bare nodes automatically reuse the
        exact same node-feature construction (padding, one-hot ID) as every
        real gene node, with no separate code path needed downstream.
    extra_edges : list of (int, int)
        New DIRECTED index pairs - ONE row per kept unordered pair (see
        edges_from_list/edges_to_list's own existing convention in
        models/GAT_biological_prior_knowledge.py: single-direction here,
        symmetrised afterwards via T.ToUndirected()) - in the FINAL,
        extended index space: gene nodes keep indices 0..n_genes-1,
        bare-marker nodes get n_genes..n_genes+len(bare_marker_names)-1, in
        `bare_marker_names` order. Already deduplicated against each other
        (no duplicate pair appears twice) - the caller is responsible for
        also deduplicating against the structural gene-gene adjacency edges
        already present, by passing the same running `existing_edges` set
        convention already used in that file (see its own dedup pattern for
        self-loops).
    """
    n_genes = len(gene_to_markers)

    marker_to_gene_idx = {}
    for g, markers in enumerate(gene_to_markers):
        for m in markers:
            # A marker's genomic window can only ever belong to the gene(s)
            # _map_genes_to_markers() assigned it to upstream; if (in an
            # unusual, overlapping-gene-window case) a marker is covered by
            # more than one active gene, the FIRST gene encountered here
            # wins - a deterministic, documented tie-break rather than an
            # arbitrary one, consistent with how a marker's node-feature
            # value is already only ever written into whichever gene node
            # actually claims it in gene_to_markers.
            marker_to_gene_idx.setdefault(m, g)

    if pair_df.shape[0] == 0:
        return [], pd.DataFrame(columns=['name', 'chromosome', 'start', 'end']), [], []

    # Bare markers: every marker that appears in pair_df but isn't covered
    # by any active gene - discovered by scanning pair_df itself (not
    # rf_selected_markers wholesale), so a bare node is only ever created
    # for a marker that actually ended up with a surviving data-driven edge
    # after top_rate filtering; an RF-selected marker with no surviving
    # interaction contributes nothing to the merged graph, exactly as an
    # RF-selected marker that happens to fall inside a gene contributes
    # nothing NEW beyond that gene's own node.
    bare_marker_names = []
    seen_bare = set()
    for col in ('marker_1', 'marker_2'):
        for m in pair_df[col]:
            if m not in marker_to_gene_idx and m not in seen_bare:
                seen_bare.add(m)
                bare_marker_names.append(m)

    if bare_marker_names:
        missing_coords = [m for m in bare_marker_names if m not in set(marker_info['name'])]
        if missing_coords:
            raise ValueError(
                f"{len(missing_coords)} bare marker(s) selected for the data-driven network "
                f"have no coordinate entry in marker_info: {missing_coords[:10]}"
                f"{', ...' if len(missing_coords) > 10 else ''}"
            )
        coords = marker_info.set_index('name').loc[bare_marker_names, ['chromosome', 'start', 'end']]
        bare_rows = coords.reset_index().rename(columns={'index': 'name'})[['name', 'chromosome', 'start', 'end']]
    else:
        bare_rows = pd.DataFrame(columns=['name', 'chromosome', 'start', 'end'])

    bare_idx_of = {m: n_genes + k for k, m in enumerate(bare_marker_names)}

    def _node_index(marker):
        if marker in marker_to_gene_idx:
            return marker_to_gene_idx[marker]
        return bare_idx_of[marker]

    extra_edges = []
    seen_extra = set()
    for _, row in pair_df.iterrows():
        i, j = _node_index(row['marker_1']), _node_index(row['marker_2'])
        if i == j:
            # Requirement 3: both markers belong to the same gene node (or,
            # in principle, the exact same bare marker) - already the same
            # node, so there is nothing to connect. Do nothing.
            continue
        key = (min(i, j), max(i, j))
        if key in seen_extra:
            continue
        seen_extra.add(key)
        # ONE directed row per kept pair - matching the existing convention
        # in models/GAT_biological_prior_knowledge.py, where the structural
        # gene-gene adjacency edge list is likewise single-direction at this
        # stage and only symmetrised afterwards via torch_geometric's
        # ToUndirected() transform. Storing both directions here as well
        # would make ToUndirected() produce a duplicated (four-times, not
        # twice) edge for every such pair, double-weighting it relative to
        # every structural edge during message passing.
        extra_edges.append((i, j))

    bare_gene_to_markers = [[m] for m in bare_marker_names]

    return bare_marker_names, bare_rows, bare_gene_to_markers, extra_edges
