"""
Preprocess/data_driven_prior_network.py
========================================

Implements requirements 2 and 3 of the "biological prior network data-driven
upgrade" spec:

  requirement 2 - once a biological prior-knowledge network has been
  resolved (uploaded, or generated by FLASH-P), optionally build a SECOND,
  data-driven interaction network over the SAME markers RF filtering
  selected (Preprocess/RF_marker_filtering.py's top-M/top-Y% marker set),
  using the identical pairwise-Shapley-interaction algorithm
  models/GAT_prior_knowledge.py already uses - just restricted to that
  smaller, RF-selected marker set instead of every marker, and reusing RF
  filtering's own fitted forest's hyperparameters (with an optional
  n_estimators override) rather than hardcoding new ones.

  requirement 3 - merge that data-driven network into the biological
  network:
    - a data-driven edge between two markers that both fall inside the
      SAME gene's window: no-op (they're already the same graph node).
    - a data-driven edge between a marker inside a gene's window and a
      marker with no gene (a "bare" marker, RF-selected but outside every
      gene): an edge from the bare-marker node to that gene node.
    - a data-driven edge between two markers in DIFFERENT genes' windows:
      an edge between those two gene nodes, if one doesn't already exist.
    - a data-driven edge between two bare markers: an edge between their
      two bare-marker nodes.
  Every resulting node - gene or bare-marker - still gets a self-loop, via
  the SAME blanket self-loop step models/GAT_biological_prior_knowledge.py
  already applies to every node in its (extended) node list; nothing here
  needs to special-case self-loops itself.

Design note - why this is a separate module and not inlined into
models/GAT_biological_prior_knowledge.py
--------------------------------------------------------------------------
Keeping the RF-selection + Shapley-interaction-search + network-merge logic
here, called from GAT_biological_prior_knowledge.py rather than written
inline there, mirrors how Preprocess/gene_network_prior.py already holds
the "biological network -> gene list + gene-gene adjacency" logic the model
file calls into: the model file orchestrates graph *construction* for
PyTorch Geometric, while the actual data-driven decisions (which markers
survive, which pairs interact, how the two networks combine) live in a
plain-pandas/numpy module that's easy to unit test and reuse (e.g. from
genomic_prediction.py's own "other models restricted to this marker pool"
preview logic - see OTHER_MODELS_MARKER_SOURCE == 'gene_network_plus_rf').
"""

import numpy as np
import pandas as pd
import shap
from sklearn.ensemble import RandomForestRegressor

from Preprocess.RF_marker_filtering import select_rf_markers
from Preprocess.LD_pruning import LD_pruning
from pipeline_utils import get_active_compute_resources
from models.interaction_extraction import tree_shap_interactions


def select_markers_for_data_driven_network(train_x, train_y, rf_config):
    """Requirement 2: "reuse the trained RF used in the RF filtering" to
    decide which markers feed the data-driven network - i.e. run the exact
    same selection RF_marker_filtering() would (same config, same
    percent/count mode), on the SAME (train_x, train_y) RF filtering itself
    would see.

    This is a thin, explicitly-named wrapper around
    Preprocess.RF_marker_filtering.select_rf_markers - kept as its own
    function (rather than calling select_rf_markers directly from
    GAT_biological_prior_knowledge.py) so the "requirement 2" intent is
    named at the call site, and so a future change to exactly what "reuse
    RF filtering" means only has one place to change.

    Returns
    -------
    (selected_markers, fitted_rf) : (list of str, RandomForestRegressor)
        selected_markers is in original column order (see
        select_rf_markers's own docstring); fitted_rf is the forest fit on
        every marker in train_x (i.e. BEFORE narrowing to
        selected_markers) - kept only for its hyperparameters (n_estimators
        etc.), read back out in compute_data_driven_interactions() below,
        since a forest fit on the full marker set cannot itself be reused
        for shap_interaction_values() restricted to a narrower column set.
    """
    selected_markers, fitted_rf, _ = select_rf_markers(train_x, train_y, rf_config)
    return selected_markers, fitted_rf


def compute_data_driven_interactions(train_x_selected, train_y, base_rf_config, top_rate,
                                       n_estimators_override=None, sample_size=50, random_state=40):
    """Requirement 2: the SAME pairwise-Shapley-interaction algorithm as
    models/GAT_prior_knowledge.py's own RF+SHAP interaction search
    (fit RF -> shap.TreeExplainer -> shap_interaction_values -> upper
    triangle -> top `top_rate` percent of pairs), but:
      - restricted to `train_x_selected`'s columns (the RF-selected marker
        subset from select_markers_for_data_driven_network above) instead
        of every marker in the genotype table, and
      - fit with `base_rf_config`'s own hyperparameters (mirroring the RF
        filtering forest's own configuration, per requirement 2's "reuse
        the trained RF used in the RF filtering") rather than
        GAT_prior_knowledge.py's hardcoded n_estimators=500, except that
        n_estimators itself can be overridden specifically for this step
        via `n_estimators_override` (e.g. because a forest tuned for
        importance-ranking over thousands of markers may want more/fewer
        trees than one used only for a SHAP interaction search over a much
        smaller, already-narrowed marker set).

    A fresh forest - not the forest fit on the full marker set by
    select_markers_for_data_driven_network - MUST be fit here: SHAP's
    TreeExplainer needs a model trained on exactly the feature columns it
    will be asked to explain, and the full-marker-set forest was trained on
    a different (larger) column set entirely.

    Parameters
    ----------
    train_x_selected : pd.DataFrame
        Genotype columns for the RF-selected markers ONLY (i.e.
        train_x[selected_markers] from the caller).
    train_y : pd.Series
        The training phenotype.
    base_rf_config : dict
        The SAME rf_config shape RF_marker_filtering.py accepts
        ('n_estimators', 'max_depth', 'max_features', 'min_samples_leaf',
        'random_state') - reused here for consistency with the filtering
        forest's own hyperparameters, per requirement 2.
    top_rate : float
        Top N percent (0, 100] of pairwise interaction strengths to keep -
        same meaning and convention as models/GAT_prior_knowledge.py's own
        `top_rate` parameter.
    n_estimators_override : int or None
        If given, used in place of base_rf_config['n_estimators'] for THIS
        forest only (does not affect RF filtering's own forest).
    sample_size : int, default 50
        Individuals sampled for shap_interaction_values(), exactly
        mirroring GAT_prior_knowledge.py's own hardcoded 50.
    random_state : int, default 40
        Mirrors GAT_prior_knowledge.py's own hardcoded random_state=40 for
        this forest, kept as a default rather than reusing
        base_rf_config['random_state'] so results are reproducible/
        comparable against the plain (non-biological-prior) GAT_prior_
        knowledge model's own interaction search run on the same data,
        unless the caller deliberately overrides it.

    Returns
    -------
    pair : pd.DataFrame, columns ['marker_1', 'marker_2', 'value']
        One row per kept unordered pair (marker_1, marker_2 are real
        marker NAMES, not positional indices - unlike GAT_prior_knowledge.py's
        own internal `pair`, which stays purely positional since it never
        needs to leave that function). Empty (zero rows, correct columns)
        if train_x_selected has fewer than 2 columns, since no pair can be
        formed.
    """
    if top_rate is None or not (0 < top_rate <= 100):
        raise ValueError(f"top_rate must be in (0, 100], got {top_rate!r}")

    marker_names = list(train_x_selected.columns)
    if len(marker_names) < 2:
        return pd.DataFrame(columns=['marker_1', 'marker_2', 'value'])

    # Patch 3, Requirement 3: this forest is deliberately ALWAYS
    # scikit-learn/CPU, even when USE_GPU_SKLEARN is set and the marker-
    # SELECTION forest just above (select_markers_for_data_driven_network()
    # -> Preprocess.RF_marker_filtering.select_rf_markers()) used cuML/GPU
    # for that step. shap.TreeExplainer (used a few lines below) requires
    # a scikit-learn-compatible tree structure that cuML's GPU forest does
    # not expose - the exact same reason models/RF.py's own SHAP-
    # interaction refit always forces a CPU forest regardless of whether
    # its main fit was GPU-backed (see that file's own comment). n_jobs is
    # still resolved from the run's shared compute-resource settings
    # (rather than hardcoded -1) so this CPU fit itself is at least
    # correctly threaded - see _resolve_n_jobs()'s docstring in
    # Preprocess/RF_marker_filtering.py for why that matters on a
    # GPU allocation.
    _resources = get_active_compute_resources()
    n_estimators = n_estimators_override if n_estimators_override is not None else base_rf_config.get('n_estimators', 500)
    rf = RandomForestRegressor(
        n_estimators=int(n_estimators),
        max_depth=base_rf_config.get('max_depth', None),
        max_features=base_rf_config.get('max_features', 'sqrt'),
        min_samples_leaf=base_rf_config.get('min_samples_leaf', 1),
        random_state=random_state,
        # Was hardcoded -1 ("every core") - not cgroup-aware, so it
        # oversubscribes/thrashes on a lean CPU allocation (e.g. a GPU
        # job) exactly like RF_marker_filtering.py's own forest did; see
        # Preprocess.RF_marker_filtering._resolve_n_jobs()'s docstring.
        n_jobs=base_rf_config.get('n_jobs') if base_rf_config.get('n_jobs') is not None
        else _resources['n_jobs'],
    )
    rf.fit(train_x_selected, train_y)

    # Update ID ver4-5, R2 (blueprint §4.4): from here on, this used to be
    # a private, byte-for-byte copy of models/GAT_prior_knowledge.py's own
    # interaction search (indexed by marker NAME afterwards instead of
    # staying purely positional) - both now call the SAME shared
    # implementation, models.interaction_extraction.tree_shap_interactions(),
    # with reduce='sum_then_abs' passed explicitly (this file's own,
    # pre-existing reduction order - see that function's own docstring for
    # why this redirection is a numeric no-op, including for the triangle-
    # selection mechanism this file used to implement inline via
    # itertools.product() + a lower-triangle mask). Only marker_1/marker_2's
    # column NAMES differ from the shared function's own canonical
    # marker1/marker2 (renamed immediately below), to keep this function's
    # own public return-column contract (merge_biological_and_data_driven_
    # networks and every other caller already expect 'marker_1'/'marker_2')
    # completely unchanged.
    sample_n = min(sample_size, train_x_selected.shape[0])
    pair = tree_shap_interactions(
        rf, shap.sample(train_x_selected, sample_n), marker_names,
        n_jobs=_resources['n_jobs'], reduce='sum_then_abs',
    )
    pair = pair.rename(columns={'marker1': 'marker_1', 'marker2': 'marker_2'})
    pair = pair[pair['value'] > 0].reset_index(drop=True)
    n_candidate_pairs = pair.shape[0]
    # Note for anyone eyeballing this against a manual "n choose 2" sanity
    # check: n_candidate_pairs is capped at len(marker_names) * (len(marker_names) - 1) / 2
    # - the number of UNIQUE unordered marker pairs - not
    # len(marker_names) * (len(marker_names) - 1) (which would double-count
    # every pair as both (i, j) and (j, i)). SHAP interaction values are
    # symmetric (interaction[i, j] == interaction[j, i] - "how much i and j
    # interact" isn't directional), so the upper triangle is zeroed above
    # specifically to avoid that double-count; n_candidate_pairs can be
    # smaller still if some pairs have exactly zero interaction.
    print(f"[data_driven_prior_network] {n_candidate_pairs} unique marker pair(s) with a "
          f"nonzero interaction score (out of at most {len(marker_names) * (len(marker_names) - 1) // 2} "
          f"possible unique pairs among {len(marker_names)} markers) - keeping the top {top_rate}% "
          f"of these by interaction strength.")
    if pair.shape[0] == 0:
        return pair
    # Bug fix (rank-based top-N%, not a quantile threshold): see
    # models.interaction_extraction.top_select()'s own "Bug fix" note for
    # the full reproduction of why a quantile-threshold comparison
    # collapses whenever a large share of the ranked column is tied at
    # the computed cutoff. `pair` is already restricted to `value > 0`
    # just above, which is exactly what keeps this call site far less
    # exposed than top_select()'s/circos_plot._select_top_interactions()'s
    # own (which rank the FULL, still zero-inflated candidate table) -
    # but the underlying quantile-comparison mechanism is the identical
    # fragile pattern, so it is corrected here too rather than left to
    # drift from the one shared, hardened implementation.
    keep_n = int(round(n_candidate_pairs * (top_rate / 100)))
    keep_n = max(0, min(keep_n, pair.shape[0]))
    pair = pair.nlargest(keep_n, 'value')
    return pair.reset_index(drop=True)


def ensure_bio_prior_merge_cache(model_name, merge_train, merge_valid, merge_test,
                                  data_driven_merge, network_cache):
    """Requirement 11 (efficiency) - PERFORMANCE FIX: this is the one
    piece of logic that decides whether the data-driven merge's two
    expensive steps (LD-pruning-then-RF-filtering, and the pairwise-
    Shapley-interaction search) actually run, or are reused from
    `network_cache`. It is a straight EXTRACTION of the caching logic
    models/GAT_biological_prior_knowledge.py used to run inline (no
    behaviour change for that call site - see it now simply calling this
    function instead) - pulled out into its own, standalone function
    specifically so genomic_prediction.py's GP() can ALSO call it
    directly, up front in the MAIN process, before dispatching this
    instance's hyperparameter-tuning trials.

    WHY THAT SECOND CALL SITE IS NECESSARY (the actual bug this function
    fixes)
    --------------------------------------------------------------------
    `network_cache` (GP()'s own `_bio_prior_merge_cache`, one fresh dict
    per prediction task) is a plain, in-memory Python dict, mutated in
    place by whichever call happens to find it empty first. That works
    perfectly when every call for a given task runs in the SAME process
    (the default, n_jobs<=1): the first call computes and caches, every
    later call in that process reuses it - exactly the "one search per
    task, not one per trial" cost this cache exists to guarantee (see
    models/GAT_biological_prior_knowledge.py's own `network_cache`
    docstring entry).

    It stops working the moment hyperparameter-tuning trials for this
    model are evaluated in SEPARATE WORKER PROCESSES - which
    HP_TUNE_PARALLEL_TRIALS=True (the default) plus N_JOBS>1 (needed for
    any real speed-up) requests for exactly this kind of expensive,
    CPU-bound model. `genomic_prediction.py::ModelTrialRunner` (the
    picklable stand-in for the model dispatch, used as
    `tune_model_hyperparameters()`'s `run_model_fn`) is pickled and sent
    to a `joblib.Parallel(backend='loky')` worker PROCESS for every
    trial (Grid/Random batches, and Bayesian's own batched, constant-liar
    rounds - see models/hyperparameter_tuning.py::_evaluate_batch()). A
    worker process's own writes to its (deserialised, PER-PROCESS COPY
    of) `network_cache` are entirely local to that process and are lost
    the instant it returns - only the trial's numeric score comes back,
    never the mutated dict. So a `network_cache` that is still cold at
    the moment trials are first dispatched gets recomputed independently
    by EVERY trial's own worker (potentially dozens of times per task,
    for a Bayesian search's `1 + init_points + n_iter` evaluations) -
    silently multiplying wall-clock time by however many trials actually
    ran, even though every one of them needed the byte-identical result
    (the merge config, `params[13]`, is deliberately never a tunable
    field - see hparam_specs.py's own module docstring - so nothing about
    it ever differs between trials).

    The fix is not to make worker-to-parent cache propagation work (that
    would need real inter-process synchronisation for something that's
    only ever read, never written, after this point) - it's simpler than
    that: call this function ONCE, here, in the driving/parent process,
    BEFORE `tune_model_hyperparameters()` is ever invoked for this
    instance this task. Because `network_cache` is captured BY VALUE
    every time a `ModelTrialRunner` gets pickled for submission to a
    worker, a `network_cache` that is already fully populated at that
    point is pickled whole, complete, into every worker - which then
    takes the (already-existing) cache-HIT branch inside
    `GAT_biological_prior_knowledge()` itself, doing zero recomputation,
    regardless of how many trials run or how many separate processes
    they run in. See genomic_prediction.py's own pre-warming call site
    (searched for by this function's own name) for exactly where this is
    invoked.

    Parameters
    ----------
    model_name : str
        This bio-prior instance's own name (e.g.
        'GAT_biological_prior_knowledge', or '..._2' for a second
        instance) - the SAME cache key
        models/GAT_biological_prior_knowledge.py's own `MODEL_NAME`
        parameter uses, so a call from here and a call from that
        function's own inline logic address the exact same
        `network_cache` entry.
    merge_train, merge_valid, merge_test : pd.DataFrame
        The TRUE, full/unrestricted-marker genotype pool for this task -
        exactly what would be passed as `GAT_biological_prior_knowledge()`'s
        own `merge_source_data` (or `data_train`/`data_valid`/`data_test`
        when that's `None`). `merge_valid` is accepted only for interface
        symmetry with that data - it is never actually read, exactly as
        the model file's own inline version never read `_merge_valid`
        either (the side pipeline only ever fits on train and narrows
        LD_pruning's own test argument, never touching validation).
    data_driven_merge : dict
        `params[13]` - e.g. `{'enabled': False}` (no-op), or the full
        merge config when enabled - see
        `models.GAT_biological_prior_knowledge.GAT_biological_prior_knowledge`'s
        own docstring for the required shape.
    network_cache : dict or None
        The task-owned cache dict (GP()'s own `_bio_prior_merge_cache`).
        `None` disables caching entirely - this function still computes
        and returns the correct result, it just never stores or reuses
        anything (byte-identical to how the model file's own inline
        version already handled `network_cache=None`).

    Returns
    -------
    (rf_selected_markers, pair_df) : (list of str, pd.DataFrame)
        `(None, None)` when `data_driven_merge['enabled']` is falsy (the
        merge feature is off) - nothing to compute or cache.
    """
    if not isinstance(data_driven_merge, dict):
        raise ValueError(
            f"data_driven_merge must be a dict, e.g. {{'enabled': False}}, got "
            f"{data_driven_merge!r} - see GAT_biological_prior_knowledge()'s own docstring."
        )
    if not data_driven_merge.get('enabled', False):
        return None, None

    rf_filter_cfg = data_driven_merge.get('rf_filter')
    if rf_filter_cfg is None:
        raise ValueError(
            "data_driven_merge['rf_filter'] is required when data_driven_merge['enabled'] "
            "is True - see GAT_biological_prior_knowledge()'s own docstring."
        )
    top_rate = data_driven_merge.get('top_rate')
    if top_rate is None:
        raise ValueError(
            "data_driven_merge['top_rate'] is required when data_driven_merge['enabled'] "
            "is True - see GAT_biological_prior_knowledge()'s own docstring."
        )

    _cache_entry = network_cache.setdefault(model_name, {}) if network_cache is not None else None
    merge_train_y = merge_train.iloc[:, -1]

    if _cache_entry is not None and 'rf_selected_markers' in _cache_entry:
        rf_selected_markers = _cache_entry['rf_selected_markers']
        print(f"[{model_name}] Data-driven merge: reusing {len(rf_selected_markers)} "
              f"RF-selected marker(s) already computed earlier this task (LD pruning/RF "
              f"filtering skipped).")
    else:
        merge_train_x = merge_train.iloc[:, :-1]
        if data_driven_merge.get('ld_prune') is not None:
            merge_train_x, _, _ = LD_pruning(
                merge_train_x, pd.DataFrame(), merge_test.iloc[:, :-1], data_driven_merge['ld_prune']
            )
        rf_selected_markers, _fitted_rf = select_markers_for_data_driven_network(
            merge_train_x, merge_train_y, rf_filter_cfg
        )
        print(f"[{model_name}] Data-driven merge: {len(rf_selected_markers)} marker(s) "
              f"selected by RF filtering (out of {merge_train_x.shape[1]} candidate(s)).")
        if _cache_entry is not None:
            _cache_entry['rf_selected_markers'] = rf_selected_markers

    if _cache_entry is not None and 'pair_df' in _cache_entry:
        pair_df = _cache_entry['pair_df']
        print(f"[{model_name}] Data-driven merge: reusing {pair_df.shape[0]} pairwise "
              f"interaction(s) already computed earlier this task.")
    else:
        # merge_train (not merge_train_x, which may not even exist in the
        # cache-hit branch above) sliced directly by rf_selected_markers -
        # selecting marker COLUMNS by name is always valid regardless of
        # whether pruning happened in this call or was reused from the
        # cache, since pruning only ever narrows which columns exist,
        # never renames/transforms them.
        pair_df = compute_data_driven_interactions(
            merge_train.loc[:, rf_selected_markers], merge_train_y, rf_filter_cfg, top_rate,
            n_estimators_override=data_driven_merge.get('shap_n_estimators_override'),
        )
        print(f"[{model_name}] Data-driven merge: {pair_df.shape[0]} unique pairwise "
              f"interaction(s) kept (top {top_rate}% - see the data_driven_prior_network log "
              f"line just above for the full candidate-pool count this percentage was taken of).")
        if _cache_entry is not None:
            _cache_entry['pair_df'] = pair_df

    return rf_selected_markers, pair_df


def merge_biological_and_data_driven_networks(gene_to_markers, pair_df, rf_selected_markers, marker_info):
    """Requirement 3: merge the data-driven pairwise-interaction network
    (`pair_df`, from compute_data_driven_interactions above) into the
    biological network's already gene-row-compacted `gene_to_markers`
    (index i <-> the i-th ACTIVE gene node - i.e. gene_to_markers as built
    by models/GAT_biological_prior_knowledge.py right before its self-loop
    step, after empty genes have already been dropped and rows re-indexed).

    Every RF-selected marker that isn't covered by any active gene becomes
    its own new "bare marker" node, appended after the existing gene nodes
    (indices n_genes, n_genes+1, ...) - this is requirement 5's upgrade of
    the old orphan-independent-node mechanism: instead of turning EVERY
    marker outside every gene into an isolated, self-loop-only node, only
    RF-selected markers become nodes at all, and they can have real,
    data-driven edges to other nodes (gene or bare), not just a self-loop.

    Parameters
    ----------
    gene_to_markers : list of list of str
        gene_to_markers[g] = every marker covering active gene node g (the
        FULL covering-marker set, not narrowed to RF-selected markers -
        see the module-level design note in models/GAT_biological_prior_
        knowledge.py for why gene coverage must stay based on the full
        marker set even when this merge feature is in use).
    pair_df : pd.DataFrame, columns ['marker_1', 'marker_2', 'value']
        From compute_data_driven_interactions - both markers are always
        drawn from rf_selected_markers (the function it was built from
        never sees any other marker).
    rf_selected_markers : list of str
        Every marker RF filtering selected for the data-driven network
        (requirement 2) - used here only to decide which markers are
        eligible to become bare nodes (a marker interacting in pair_df but
        outside every gene window must, by construction, be in this list;
        this parameter exists mainly so bare-node coordinates can be looked
        up deterministically even for a marker that ends up with no
        surviving pair after top_rate filtering - see `bare_marker_names`
        below, which is drawn from pair_df's own markers only, so this
        parameter is currently used purely for the sanity check below).
    marker_info : pd.DataFrame
        Columns chromosome, name, start, end (same file
        models/GAT_biological_prior_knowledge.py already loaded) - used to
        look up each bare marker's own coordinates for its gene_list row.

    Returns
    -------
    bare_marker_names : list of str
        RF-selected markers, in pair_df, that fall outside every gene's
        window - the new bare-marker nodes, in a stable (first-seen-in-
        pair_df) order.
    bare_rows : pd.DataFrame, columns ['name', 'chromosome', 'start', 'end']
        One row per bare marker, ready to be appended to gene_list_active.
    bare_gene_to_markers : list of list of str
        One singleton list per bare marker (`[marker_name]`), ready to be
        appended to gene_to_markers - so bare nodes automatically reuse the
        exact same node-feature construction (padding, one-hot ID) as every
        real gene node, with no separate code path needed downstream.
    extra_edges : list of (int, int)
        New DIRECTED index pairs - ONE row per kept unordered pair (see
        edges_from_list/edges_to_list's own existing convention in
        models/GAT_biological_prior_knowledge.py: single-direction here,
        symmetrised afterwards via T.ToUndirected()) - in the FINAL,
        extended index space: gene nodes keep indices 0..n_genes-1,
        bare-marker nodes get n_genes..n_genes+len(bare_marker_names)-1, in
        `bare_marker_names` order. Already deduplicated against each other
        (no duplicate pair appears twice) - the caller is responsible for
        also deduplicating against the structural gene-gene adjacency edges
        already present, by passing the same running `existing_edges` set
        convention already used in that file (see its own dedup pattern for
        self-loops).
    """
    n_genes = len(gene_to_markers)

    marker_to_gene_idx = {}
    for g, markers in enumerate(gene_to_markers):
        for m in markers:
            # A marker's genomic window can only ever belong to the gene(s)
            # _map_genes_to_markers() assigned it to upstream; if (in an
            # unusual, overlapping-gene-window case) a marker is covered by
            # more than one active gene, the FIRST gene encountered here
            # wins - a deterministic, documented tie-break rather than an
            # arbitrary one, consistent with how a marker's node-feature
            # value is already only ever written into whichever gene node
            # actually claims it in gene_to_markers.
            marker_to_gene_idx.setdefault(m, g)

    if pair_df.shape[0] == 0:
        return [], pd.DataFrame(columns=['name', 'chromosome', 'start', 'end']), [], []

    # Bare markers: every marker that appears in pair_df but isn't covered
    # by any active gene - discovered by scanning pair_df itself (not
    # rf_selected_markers wholesale), so a bare node is only ever created
    # for a marker that actually ended up with a surviving data-driven edge
    # after top_rate filtering; an RF-selected marker with no surviving
    # interaction contributes nothing to the merged graph, exactly as an
    # RF-selected marker that happens to fall inside a gene contributes
    # nothing NEW beyond that gene's own node.
    bare_marker_names = []
    seen_bare = set()
    for col in ('marker_1', 'marker_2'):
        for m in pair_df[col]:
            if m not in marker_to_gene_idx and m not in seen_bare:
                seen_bare.add(m)
                bare_marker_names.append(m)

    if bare_marker_names:
        missing_coords = [m for m in bare_marker_names if m not in set(marker_info['name'])]
        if missing_coords:
            raise ValueError(
                f"{len(missing_coords)} bare marker(s) selected for the data-driven network "
                f"have no coordinate entry in marker_info: {missing_coords[:10]}"
                f"{', ...' if len(missing_coords) > 10 else ''}"
            )
        coords = marker_info.set_index('name').loc[bare_marker_names, ['chromosome', 'start', 'end']]
        bare_rows = coords.reset_index().rename(columns={'index': 'name'})[['name', 'chromosome', 'start', 'end']]
    else:
        bare_rows = pd.DataFrame(columns=['name', 'chromosome', 'start', 'end'])

    bare_idx_of = {m: n_genes + k for k, m in enumerate(bare_marker_names)}

    def _node_index(marker):
        if marker in marker_to_gene_idx:
            return marker_to_gene_idx[marker]
        return bare_idx_of[marker]

    extra_edges = []
    seen_extra = set()
    for _, row in pair_df.iterrows():
        i, j = _node_index(row['marker_1']), _node_index(row['marker_2'])
        if i == j:
            # Requirement 3: both markers belong to the same gene node (or,
            # in principle, the exact same bare marker) - already the same
            # node, so there is nothing to connect. Do nothing.
            continue
        key = (min(i, j), max(i, j))
        if key in seen_extra:
            continue
        seen_extra.add(key)
        # ONE directed row per kept pair - matching the existing convention
        # in models/GAT_biological_prior_knowledge.py, where the structural
        # gene-gene adjacency edge list is likewise single-direction at this
        # stage and only symmetrised afterwards via torch_geometric's
        # ToUndirected() transform. Storing both directions here as well
        # would make ToUndirected() produce a duplicated (four-times, not
        # twice) edge for every such pair, double-weighting it relative to
        # every structural edge during message passing.
        extra_edges.append((i, j))

    bare_gene_to_markers = [[m] for m in bare_marker_names]

    return bare_marker_names, bare_rows, bare_gene_to_markers, extra_edges
